[2024-04-05T20:49:33.731+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgre_operator.create_table_task manual__2024-04-05T20:12:33.404503+00:00 [queued]>
[2024-04-05T20:49:33.750+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgre_operator.create_table_task manual__2024-04-05T20:12:33.404503+00:00 [queued]>
[2024-04-05T20:49:33.752+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-05T20:49:33.779+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-04-05 20:12:33.404503+00:00
[2024-04-05T20:49:33.789+0000] {standard_task_runner.py:60} INFO - Started process 1020 to run task
[2024-04-05T20:49:33.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgre_operator', 'create_table_task', 'manual__2024-04-05T20:12:33.404503+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator_extract.py', '--cfg-path', '/tmp/tmpipvi3dns']
[2024-04-05T20:49:33.796+0000] {standard_task_runner.py:88} INFO - Job 553: Subtask create_table_task
[2024-04-05T20:49:33.858+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgre_operator.create_table_task manual__2024-04-05T20:12:33.404503+00:00 [running]> on host 7f6ff1f67725
[2024-04-05T20:49:33.960+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_postgre_operator' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T20:12:33.404503+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-05T20:12:33.404503+00:00'
[2024-04-05T20:49:33.961+0000] {sql.py:276} INFO - Executing: 
    CREATE TABLE shooting (
    incident_ID SERIAL,
    incident_num VARCHAR(100) ,
    shooting_date VARCHAR(100),
    district varchar(100),
    Shooting_type INTEGER,
    Gender VARCHAR(100),
    Race VARCHAR(100),
    Ethnicity VARCHAR(100),
    multiple_victims INTEGER
    );
    
[2024-04-05T20:49:33.972+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T20:49:33.984+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T20:49:34.022+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE shooting (
    incident_ID SERIAL,
    incident_num VARCHAR(100) ,
    shooting_date VARCHAR(100),
    district varchar(100),
    Shooting_type INTEGER,
    Gender VARCHAR(100),
    Race VARCHAR(100),
    Ethnicity VARCHAR(100),
    multiple_victims INTEGER
    );
    , parameters: None
[2024-04-05T20:49:34.036+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(shooting_incident_id_seq, 2200) already exists.

[2024-04-05T20:49:34.045+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_postgre_operator, task_id=create_table_task, execution_date=20240405T201233, start_date=20240405T204933, end_date=20240405T204934
[2024-04-05T20:49:34.059+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 553 for task create_table_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(shooting_incident_id_seq, 2200) already exists.
; 1020)
[2024-04-05T20:49:34.088+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-05T20:49:34.102+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-05T20:49:34.117+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
