[2024-04-05T21:15:01.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgre_operator.alter_table_task manual__2024-04-05T00:55:00.248811+00:00 [queued]>
[2024-04-05T21:15:01.658+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgre_operator.alter_table_task manual__2024-04-05T00:55:00.248811+00:00 [queued]>
[2024-04-05T21:15:01.659+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-05T21:15:02.200+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): alter_table_task> on 2024-04-05 00:55:00.248811+00:00
[2024-04-05T21:15:02.223+0000] {standard_task_runner.py:60} INFO - Started process 4385 to run task
[2024-04-05T21:15:02.229+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgre_operator', 'alter_table_task', 'manual__2024-04-05T00:55:00.248811+00:00', '--job-id', '1020', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator_extract.py', '--cfg-path', '/tmp/tmpnvcx5hcg']
[2024-04-05T21:15:02.242+0000] {standard_task_runner.py:88} INFO - Job 1020: Subtask alter_table_task
[2024-04-05T21:15:02.480+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgre_operator.alter_table_task manual__2024-04-05T00:55:00.248811+00:00 [running]> on host 7f6ff1f67725
[2024-04-05T21:15:02.925+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_postgre_operator' AIRFLOW_CTX_TASK_ID='alter_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T00:55:00.248811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-05T00:55:00.248811+00:00'
[2024-04-05T21:15:02.934+0000] {sql.py:276} INFO - Executing: 
    ALTER TABLE shooting
    ADD CONSTRAINT incident_pk PRIMARY KEY (incident_ID);
    
[2024-04-05T21:15:02.970+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T21:15:03.005+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T21:15:03.103+0000] {sql.py:457} INFO - Running statement: 
    ALTER TABLE shooting
    ADD CONSTRAINT incident_pk PRIMARY KEY (incident_ID);
    , parameters: None
[2024-04-05T21:15:03.118+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "shooting" does not exist

[2024-04-05T21:15:03.146+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_postgre_operator, task_id=alter_table_task, execution_date=20240405T005500, start_date=20240405T211501, end_date=20240405T211503
[2024-04-05T21:15:03.188+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1020 for task alter_table_task (relation "shooting" does not exist
; 4385)
[2024-04-05T21:15:03.235+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-05T21:15:03.300+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
