[2024-04-05T21:14:30.971+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgre_operator.create_table_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-04-05T21:14:31.012+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgre_operator.create_table_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-04-05T21:14:31.014+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-05T21:14:31.066+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-03-28 00:00:00+00:00
[2024-04-05T21:14:31.082+0000] {standard_task_runner.py:60} INFO - Started process 3912 to run task
[2024-04-05T21:14:31.088+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgre_operator', 'create_table_task', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '875', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator_extract.py', '--cfg-path', '/tmp/tmp1wj2dmih']
[2024-04-05T21:14:31.094+0000] {standard_task_runner.py:88} INFO - Job 875: Subtask create_table_task
[2024-04-05T21:14:31.253+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgre_operator.create_table_task scheduled__2024-03-28T00:00:00+00:00 [running]> on host 7f6ff1f67725
[2024-04-05T21:14:31.498+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_postgre_operator' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2024-04-05T21:14:31.504+0000] {sql.py:276} INFO - Executing: 
    CREATE TABLE shooting (
    incident_ID SERIAL,
    incident_num VARCHAR(100) ,
    shooting_date VARCHAR(100),
    district varchar(100),
    Shooting_type INTEGER,
    Gender VARCHAR(100),
    Race VARCHAR(100),
    Ethnicity VARCHAR(100),
    multiple_victims INTEGER
    );
    
[2024-04-05T21:14:31.533+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T21:14:31.577+0000] {base.py:83} INFO - Using connection ID 'postgres_webik' for task execution.
[2024-04-05T21:14:31.688+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE shooting (
    incident_ID SERIAL,
    incident_num VARCHAR(100) ,
    shooting_date VARCHAR(100),
    district varchar(100),
    Shooting_type INTEGER,
    Gender VARCHAR(100),
    Race VARCHAR(100),
    Ethnicity VARCHAR(100),
    multiple_victims INTEGER
    );
    , parameters: None
[2024-04-05T21:14:31.707+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "shooting" already exists

[2024-04-05T21:14:31.755+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_postgre_operator, task_id=create_table_task, execution_date=20240328T000000, start_date=20240405T211430, end_date=20240405T211431
[2024-04-05T21:14:31.835+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 875 for task create_table_task (relation "shooting" already exists
; 3912)
[2024-04-05T21:14:31.887+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-05T21:14:32.270+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-05T21:14:32.295+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
